language: php

php:
  - '7.3'
  - '7.4'
  - '8.0'
  - 'nightly'

sudo: false

before_install:
  - travis_retry composer self-update --2

install:
  - composer update

script:
  - XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
  - php vendor/bin/php-coveralls -v
